#ifndef SPRM_H
#define SPRM_H

#include "doc.h"

enum {
	sgcPar   = 0x1, // paragraph
	sgcCha   = 0x2, // character property
	sgcPic   = 0x3, // picture
	sgcSec   = 0x4, // section
	sgcTab   = 0x5, // table
};

/* 2.6.1 Character Properties
 * A Prl with a sprm.sgc of 2 modifies a character
 * property.*/ 
enum {
	sprmCFRMarkDel        = 0x00,
	sprmCFRMarkIns        = 0x01,
	sprmCFFldVanish       = 0x02,
	sprmCPicLocation      = 0x03,
	sprmCIbstRMark        = 0x04,
	sprmCDttmRMark        = 0x05,
	sprmCFData            = 0x06,
	sprmCIdslRMark        = 0x07,
	sprmCSymbol           = 0x09,
	sprmCFOle2            = 0x0A,
	sprmCHighlight        = 0x0C,
	sprmCFWebHidden       = 0x11,
	sprmCRsidProp         = 0x15,
	sprmCRsidText         = 0x16,
	sprmCRsidRMDel        = 0x17,
	sprmCFSpecVanish      = 0x18,
	sprmCFMathPr          = 0x1A,
	sprmCIstd             = 0x30,
	sprmCIstdPermute      = 0x31,
	sprmCPlain            = 0x33,
	sprmCKcd              = 0x34,
	sprmCFBold            = 0x35,
	sprmCFItalic          = 0x36,
	sprmCFStrike          = 0x37,
	sprmCFOutline         = 0x38,
	sprmCFShadow          = 0x39,
	sprmCFSmallCaps       = 0x3A,
	sprmCFCaps            = 0x3B,
	sprmCFVanish          = 0x3C,
	sprmCKul              = 0x3E,
	sprmCDxaSpace         = 0x40,
	sprmCIco              = 0x42,
	sprmCHps              = 0x43,
	sprmCHpsPos           = 0x45,
	sprmCMajority         = 0x47,
	sprmCIss              = 0x48,
  sprmCHpsKern          = 0x4B,
	sprmCHresi            = 0x4E,
	sprmCRgFtc0           = 0x4F,
	sprmCRgFtc1           = 0x50,
	sprmCRgFtc2           = 0x51,
	sprmCCharScale        = 0x52,
	sprmCFDStrike         = 0x53,
	sprmCFImprint         = 0x54,
	sprmCFSpec            = 0x55,
	sprmCFObj             = 0x56,
	sprmCPropRMark90      = 0x57,
	sprmCFEmboss          = 0x58,
	sprmCSfxText          = 0x59,
	sprmCFBiDi            = 0x5A,
	sprmCFBoldBi          = 0x5C,
	sprmCFItalicBi        = 0x5D,
	sprmCFtcBi            = 0x5E,
	sprmCLidBi            = 0x5F,
	sprmCIcoBi            = 0x60,
	sprmCHpsBi            = 0x61,
	sprmCDispFldRMark     = 0x62,
	sprmCIbstRMarkDel     = 0x63,
	sprmCDttmRMarkDel     = 0x64,
	sprmCBrc80            = 0x65,
	sprmCShd80            = 0x66,
	sprmCIdslRMarkDel     = 0x67,
	sprmCFUsePgsuSettings = 0x68,
	sprmCRgLid0_80        = 0x6D,
	sprmCRgLid1_80        = 0x6E,
	sprmCIdctHint         = 0x6F,
	sprmCCv               = 0x70,
	sprmCShd              = 0x71,
	sprmCBrc              = 0x72,
	sprmCRgLid0           = 0x73,
	sprmCRgLid1           = 0x74,
	sprmCFNoProof         = 0x75,
	sprmCFitText          = 0x76,
	sprmCCvUl             = 0x77,
	sprmCFELayout         = 0x78,
	sprmCLbcCRJ           = 0x79,
	sprmCFComplexScripts  = 0x82,
	sprmCWall             = 0x83,
	sprmCCnf              = 0x85,
	sprmCNeedFontFixup    = 0x86,
	sprmCPbiIBullet       = 0x87,
	sprmCPbiGrf           = 0x88,
	sprmCPropRMark        = 0x89,
	sprmCFSdtVanish       = 0x90,
};

/* 2.6.2 Paragraph Properties
 * A Prl with a sprm.sgc of 1 modifies a paragraph
 * property*/
enum {
	sprmPIstd               = 0x00,
	sprmPIstdPermute        = 0x01,
	sprmPIncLvl             = 0x02,
	sprmPJc80               = 0x03,
	sprmPFKeep              = 0x05,
	sprmPFKeepFollow        = 0x06,
	sprmPFPageBreakBefore   = 0x07,
	sprmPIlvl               = 0x0A,
	sprmPIlfo               = 0x0B,
	sprmPFNoLineNumb        = 0x0C,
	sprmPChgTabsPapx        = 0x0D,
	sprmPDxaRight80         = 0x0E,
	sprmPDxaLeft80          = 0x0F,
	sprmPNest80             = 0x10,
	sprmPDxaLeft180         = 0x11,
	sprmPDyaLine            = 0x12,
	sprmPDyaBefore          = 0x13,
	sprmPDyaAfter           = 0x14,
	sprmPChgTabs            = 0x15,
	sprmPFInTable           = 0x16,
	sprmPFTtp               = 0x17,
	sprmPDxaAbs             = 0x18,
	sprmPDyaAbs             = 0x19,
	sprmPDxaWidth           = 0x1A,
	sprmPPc                 = 0x1B,
	sprmPWr                 = 0x23,
	sprmPBrcTop80           = 0x24,
	sprmPBrcLeft80          = 0x25,
	sprmPBrcBottom80        = 0x26,
	sprmPBrcRight80         = 0x27,
	sprmPBrcBetween80       = 0x28,
	sprmPBrcBar80           = 0x29,
	sprmPFNoAutoHyph        = 0x2A,
	sprmPWHeightAbs         = 0x2B,
	sprmPDcs                = 0x2C,
	sprmPShd80              = 0x2D,
	sprmPDyaFromText        = 0x2E,
	sprmPDxaFromText        = 0x2F,
	sprmPFLocked            = 0x30,
	sprmPFWidowControl      = 0x31,
	sprmPFKinsoku           = 0x33,
	sprmPFWordWrap          = 0x34,
	sprmPFOverflowPunct     = 0x35,
	sprmPFTopLinePunct      = 0x36,
	sprmPFAutoSpaceDE       = 0x37,
	sprmPFAutoSpaceDN       = 0x38,
	sprmPWAlignFont         = 0x39,
	sprmPFrameTextFlow      = 0x3A,
	sprmPOutLvl             = 0x40,
	sprmPFBiDi              = 0x41,
	sprmPNumRM              = 0x45,
	sprmPHugePapx           = 0x46,
	sprmPFUsePgsuSettings   = 0x47,
	sprmPFAdjustRight       = 0x48,
	sprmPItap               = 0x49,
	sprmPDtap               = 0x4A,
	sprmPFInnerTableCell    = 0x4B,
	sprmPFInnerTtp          = 0x4C,
	sprmPShd                = 0x4D,
	sprmPBrcTop             = 0x4E,
	sprmPBrcLeft            = 0x4F,
	sprmPBrcBottom          = 0x50,
	sprmPBrcRight           = 0x51,
	sprmPBrcBetween         = 0x52,
	sprmPBrcBar             = 0x53,
	sprmPDxcRight           = 0x55,
	sprmPDxcLeft            = 0x56,
	sprmPDxcLeft1           = 0x57,
	sprmPDylBefore          = 0x58,
	sprmPDylAfter           = 0x59,
	sprmPFOpenTch           = 0x5A,
	sprmPFDyaBeforeAuto     = 0x5B,
	sprmPFDyaAfterAuto      = 0x5C,
	sprmPDxaRight           = 0x5D,
	sprmPDxaLeft            = 0x5E,
	sprmPNest               = 0x5F,
	sprmPDxaLeft1           = 0x60,
	sprmPJc                 = 0x61,
	sprmPFNoAllowOverlap    = 0x62,
	sprmPWall               = 0x64,
	sprmPIpgp               = 0x65,
	sprmPCnf                = 0x66,
	sprmPRsid               = 0x67,
	sprmPIstdListPermute    = 0x69,
	sprmPTableProps         = 0x6B,
	sprmPTIstdInfo          = 0x6C,
	sprmPFContextualSpacing = 0x6D,
	sprmPPropRMark          = 0x6F,
	sprmPFMirrorIndents     = 0x70,
	sprmPTtwo               = 0x71,
};

/* 2.6.3 Table Properties
 * A Prl with a sprm.sgc of 5 modifies a table property.*/
enum {
	sprmTJc90                = 0x00,
	sprmTDxaLeft             = 0x01,
	sprmTDxaGapHalf          = 0x02,
	sprmTFCantSplit90        = 0x03,
	sprmTTableHeader         = 0x04,
	sprmTTableBorders80      = 0x05,
	sprmTDyaRowHeight        = 0x07,
	sprmTDefTable            = 0x08,
	sprmTDefTableShd80       = 0x09,
	sprmTTlp                 = 0x0A,
	sprmTFBiDi               = 0x0B,
	sprmTDefTableShd3rd      = 0x0C,
	sprmTPc                  = 0x0D,
	sprmTDxaAbs              = 0x0E,
	sprmTDyaAbs              = 0x0F,
	sprmTDxaFromText         = 0x10,
	sprmTDyaFromText         = 0x11,
	sprmTDefTableShd         = 0x12,
	sprmTTableBorders        = 0x13,
	sprmTTableWidth          = 0x14,
	sprmTFAutofit            = 0x15,
	sprmTDefTableShd2nd      = 0x16,
	sprmTWidthBefore         = 0x17,
	sprmTWidthAfter          = 0x18,
	sprmTFKeepFollow         = 0x19,
	sprmTBrcTopCv            = 0x1A,
	sprmTBrcLeftCv           = 0x1B,
	sprmTBrcBottomCv         = 0x1C,
	sprmTBrcRightCv          = 0x1D,
	sprmTDxaFromTextRight    = 0x1E,
	sprmTDyaFromTextBottom   = 0x1F,
	sprmTSetBrc80            = 0x20,
	sprmTInsert              = 0x21,
	sprmTDelete              = 0x22,
	sprmTDxaCol              = 0x23,
	sprmTMerge               = 0x24,
	sprmTSplit               = 0x25,
	sprmTTextFlow            = 0x29,
	sprmTVertMerge           = 0x2B,
	sprmTVertAlign           = 0x2C,
	sprmTSetShd              = 0x2D,
	sprmTSetShdOdd           = 0x2E,
	sprmTSetBrc              = 0x2F,
	sprmTCellPadding         = 0x32,
	sprmTCellSpacingDefault  = 0x33,
	sprmTCellPaddingDefault  = 0x34,
	sprmTCellWidth           = 0x35,
	sprmTFitText             = 0x36,
	sprmTFCellNoWrap         = 0x39,
	sprmTIstd                = 0x3A,
	sprmTCellPaddingStyle    = 0x3E,
	sprmTCellFHideMark       = 0x42,
	sprmTSetShdTable         = 0x60,
	sprmTWidthIndent         = 0x61,
	sprmTCellBrcType         = 0x62,
	sprmTFBiDi90             = 0x64,
	sprmTFNoAllowOverlap     = 0x65,
	sprmTFCantSplit          = 0x66,
	sprmTPropRMark           = 0x67,
	sprmTWall                = 0x68,
	sprmTIpgp                = 0x69,
	sprmTCnf                 = 0x6A,
	sprmTDefTableShdRaw      = 0x70,
	sprmTDefTableShdRaw2nd   = 0x71,
	sprmTDefTableShdRaw3rd   = 0x72,
	sprmTRsid                = 0x79,
	sprmTCellVertAlignStyle  = 0x7C,
	sprmTCellNoWrapStyle     = 0x7D,
	sprmTCellBrcTopStyle     = 0x7F,
	sprmTCellBrcBottomStyle  = 0x80,
	sprmTCellBrcLeftStyle    = 0x81,
	sprmTCellBrcRightStyle   = 0x82,
	sprmTCellBrcInsideHStyle = 0x83,
	sprmTCellBrcInsideVStyle = 0x84,
	sprmTCellBrcTL2BRStyle   = 0x85,
	sprmTCellBrcTR2BLStyle   = 0x86,
	sprmTCellShdStyle        = 0x87,
	sprmTCHorzBands          = 0x88,
	sprmTCVertBands          = 0x89,
	sprmTJc                  = 0x8A,
};

/* 2.6.4 Section Properties
 * A Prl structure with a sprm.sgc of 4 modifies a section
 * property.*/
enum {
	sprmScnsPgn        = 0x00,
	sprmSiHeadingPgn   = 0x01,
	sprmSDxaColWidth   = 0x03,
	sprmSDxaColSpacing = 0x04,
	sprmSFEvenlySpaced = 0x05,
	sprmSFProtected    = 0x06,
	sprmSDmBinFirst    = 0x07,
	sprmSDmBinOther    = 0x08,
	sprmSBkc           = 0x09,
	sprmSFTitlePage    = 0x0A,
	sprmSCcolumns      = 0x0B,
	sprmSDxaColumns    = 0x0C,
	sprmSNfcPgn        = 0x0E,
	sprmSFPgnRestart   = 0x11,
	sprmSFEndnote      = 0x12,
	sprmSLnc           = 0x13,
	sprmSNLnnMod       = 0x15,
	sprmSDxaLnn        = 0x16,
	sprmSDyaHdrTop     = 0x17,
	sprmSDyaHdrBottom  = 0x18,
	sprmSLBetween      = 0x19,
	sprmSVjc           = 0x1A,
	sprmSLnnMin        = 0x1B,
	sprmSPgnStart97    = 0x1C,
	sprmSBOrientation  = 0x1D,
	sprmSXaPage        = 0x1F,
	sprmSYaPage        = 0x20,
	sprmSDxaLeft       = 0x21,
	sprmSDxaRight      = 0x22,
	sprmSDyaTop        = 0x23,
	sprmSDyaBottom     = 0x24,
	sprmSDzaGutter     = 0x25,
	sprmSDmPaperReq    = 0x26,
	sprmSFBiDi         = 0x28,
	sprmSFRTLGutter    = 0x2A,
	sprmSBrcTop80      = 0x2B,
	sprmSBrcLeft80     = 0x2C,
	sprmSBrcBottom80   = 0x2D,
	sprmSPgbProp       = 0x2F,
	sprmSDxtCharSpace  = 0x30,
	sprmSDyaLinePitch  = 0x31,
	sprmSClm           = 0x32,
	sprmSTextFlow      = 0x33,
	sprmSBrcTop        = 0x34,
	sprmSBrcLeft       = 0x35,
	sprmSBrcBottom     = 0x36,
	sprmSBrcRight      = 0x37,
	sprmSWall          = 0x39,
	sprmSRsid          = 0x3A,
	sprmSFpc           = 0x3B,
	sprmSRncFtn        = 0x3C,
	sprmSRncEdn        = 0x3E,
	sprmSNFtn          = 0x3F,
	sprmSNfcFtnRef     = 0x40,
	sprmSNEdn          = 0x41,
	sprmSNfcEdnRef     = 0x42,
	sprmSPropRMark     = 0x43,
	sprmSPgnStart      = 0x44,
};

/* 2.6.5 Picture Properties
 * A Prl with a sprm.sgc of 3 modifies a picture property.*/
enum {
	sprmPicBrcTop80    = 0x02,
	sprmPicBrcLeft80   = 0x03,
	sprmPicBrcBottom80 = 0x04,
	sprmPicBrcRight80  = 0x05,
	sprmPicBrcTop      = 0x08,
	sprmPicBrcLeft     = 0x09,
	sprmPicBrcBottom   = 0x0A,
	sprmPicBrcRight    = 0x0B,
};

#endif /* ifndef SPRM_H */
